DROP DATABASE IF EXISTS queue;
CREATE DATABASE IF NOT EXISTS queue;
USE queue;
DROP TABLE IF EXISTS tasks;
CREATE TABLE tasks (
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    uuid TEXT NOT NULL,
    status INT(11) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
